/*Copyright (c) 2018-2019 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.basicsanity.testingdb_sql.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.basicsanity.testingdb_sql.AllTypesTable;


/**
 * ServiceImpl object for domain model class AllTypesTable.
 *
 * @see AllTypesTable
 */
@Service("TestingDB_SQL.AllTypesTableService")
@Validated
public class AllTypesTableServiceImpl implements AllTypesTableService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AllTypesTableServiceImpl.class);


    @Autowired
    @Qualifier("TestingDB_SQL.AllTypesTableDao")
    private WMGenericDao<AllTypesTable, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<AllTypesTable, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "TestingDB_SQLTransactionManager")
    @Override
    public AllTypesTable create(AllTypesTable allTypesTable) {
        LOGGER.debug("Creating a new AllTypesTable with information: {}", allTypesTable);

        AllTypesTable allTypesTableCreated = this.wmGenericDao.create(allTypesTable);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(allTypesTableCreated);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public AllTypesTable getById(Integer alltypestableId) {
        LOGGER.debug("Finding AllTypesTable by id: {}", alltypestableId);
        return this.wmGenericDao.findById(alltypestableId);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public AllTypesTable findById(Integer alltypestableId) {
        LOGGER.debug("Finding AllTypesTable by id: {}", alltypestableId);
        try {
            return this.wmGenericDao.findById(alltypestableId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No AllTypesTable found with id: {}", alltypestableId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public List<AllTypesTable> findByMultipleIds(List<Integer> alltypestableIds, boolean orderedReturn) {
        LOGGER.debug("Finding AllTypesTables by ids: {}", alltypestableIds);

        return this.wmGenericDao.findByMultipleIds(alltypestableIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "TestingDB_SQLTransactionManager")
    @Override
    public AllTypesTable update(AllTypesTable allTypesTable) {
        LOGGER.debug("Updating AllTypesTable with information: {}", allTypesTable);

        this.wmGenericDao.update(allTypesTable);
        this.wmGenericDao.refresh(allTypesTable);

        return allTypesTable;
    }

    @Transactional(value = "TestingDB_SQLTransactionManager")
    @Override
    public AllTypesTable delete(Integer alltypestableId) {
        LOGGER.debug("Deleting AllTypesTable with id: {}", alltypestableId);
        AllTypesTable deleted = this.wmGenericDao.findById(alltypestableId);
        if (deleted == null) {
            LOGGER.debug("No AllTypesTable found with id: {}", alltypestableId);
            throw new EntityNotFoundException(String.valueOf(alltypestableId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "TestingDB_SQLTransactionManager")
    @Override
    public void delete(AllTypesTable allTypesTable) {
        LOGGER.debug("Deleting AllTypesTable with {}", allTypesTable);
        this.wmGenericDao.delete(allTypesTable);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public Page<AllTypesTable> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all AllTypesTables");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public Page<AllTypesTable> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all AllTypesTables");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service TestingDB_SQL for table AllTypesTable to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service TestingDB_SQL for table AllTypesTable to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "TestingDB_SQLTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}