/*Copyright (c) 2018-2019 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.basicsanity.testingdb_sql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Orders generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Orders`")
public class Orders implements Serializable {

    private Integer orderId;
    private String productName;
    private int quantity;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] rowRevision;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`OrderID`", nullable = false, scale = 0, precision = 10)
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Column(name = "`ProductName`", nullable = false, length = 50)
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "`Quantity`", nullable = false, scale = 0, precision = 10)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "`RowRevision`", nullable = false)
    public byte[] getRowRevision() {
        return this.rowRevision;
    }

    public void setRowRevision(byte[] rowRevision) {
        this.rowRevision = rowRevision;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Orders)) return false;
        final Orders orders = (Orders) o;
        return Objects.equals(getOrderId(), orders.getOrderId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderId());
    }
}