/*Copyright (c) 2018-2019 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.basicsanity.testingdb_sql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * VirtualOnaToOnaChild generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Virtual Ona to Ona Child`")
@IdClass(VirtualOnaToOnaChildId.class)
public class VirtualOnaToOnaChild implements Serializable {

    private Integer virtualOnaToOnaParent;
    private String column3;

    @Id
    @Column(name = "`Virtual Ona to Ona Parent`", nullable = true, scale = 0, precision = 10)
    public Integer getVirtualOnaToOnaParent() {
        return this.virtualOnaToOnaParent;
    }

    public void setVirtualOnaToOnaParent(Integer virtualOnaToOnaParent) {
        this.virtualOnaToOnaParent = virtualOnaToOnaParent;
    }

    @Id
    @Column(name = "`COLUMN3`", nullable = true, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VirtualOnaToOnaChild)) return false;
        final VirtualOnaToOnaChild virtualOnaToOnaChild = (VirtualOnaToOnaChild) o;
        return Objects.equals(getVirtualOnaToOnaParent(), virtualOnaToOnaChild.getVirtualOnaToOnaParent()) &&
                Objects.equals(getColumn3(), virtualOnaToOnaChild.getColumn3());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVirtualOnaToOnaParent(),
                getColumn3());
    }
}